<?php

namespace AppBundle\Repository;

/**
 * VoituresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoituresRepository extends \Doctrine\ORM\EntityRepository
{
}
