places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

app:
    resource: "@AppBundle/Controller/"
    type:     rest
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check
